### ISSUE TITLE
Bug in assets.xml file on odoo 16

### ISSUE THREAD

**Issue by rrawann** [Coding-Dodo/owl_tutorial_views#4]
odoo.tools.convert.ParseError: while parsing None:3, somewhere inside
<data name="assets_backend" inherit_id="web.assets_backend">
        <xpath expr="." position="inside">
            <script type="text/javascript" src="/owl_tutorial_views/static/src/components/tree_item/TreeItem.js"/>

            <script type="text/javascript" src="/owl_tutorial_views/static/src/owl_tree_view/owl_tree_view.js"/>
            <script type="text/javascript" src="/owl_tutorial_views/static/src/owl_tree_view/owl_tree_model.js"/>
            <script type="text/javascript" src="/owl_tutorial_views/static/src/owl_tree_view/owl_tree_controller.js"/>
            <script type="text/javascript" src="/owl_tutorial_views/static/src/owl_tree_view/owl_tree_renderer.js"/>
        </xpath>
        
    </data>

**Comment by PhilDL** [comment]
Hello @rrawann, from the look of your error you are using the main branch (14.0) version. 

There is no branch for Odoo 16 but there is one for Odoo 15 that uses the assets import from `__manifest__.py`. 

You could switch on branch 15.0 and then try to upgrade to 16.0.

**Comment by rrawann** [comment]
OK , Thank you @PhilDL
